### PR TITLE
Updated to new package version 0.5.1

### PR DESCRIPTION
**Pull request by loli**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by sarthakpati** [comment]
I am assuming this supercedes #13 and that can be ignored?

**Comment by loli** [comment]
> I am assuming this supercedes #13 and that can be ignored?

Indeed, it does. One patch needed an update, too.

**Review by sarthakpati — APPROVED** [review]
Sounds good, thanks! LGTM

**Comment by oskar-maier-ms** [comment]
Azure Pipelines fail after merging. Can't really figure out why. Any ideas?

**Pull request merged**
